apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pet-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pet-deploy
    spec:
      containers:
        - name: pet-server
          image: marcecaro/pet:{{ .Values.commit }}
          imagePullPolicy: Always
          # ports:
          # - containerPort: 5000
 