apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pet
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /pet
        backend:
          serviceName: pet
          servicePort: 80
