#!/bin/bash
set -e
MUTE=yes ./get_kind_impacted rule  $1 $2

if [ -s "/tmp/impacted_rules" ] 
then
	echo ""
    echo ""
    echo "Zipping Artifacts"
    cat  /tmp/impacted_rules | grep "_package" | xargs -L 1 bazel build   
else
	echo ""
    echo ""
    echo "No Artifact impacted... (ignoring)"
fi
