#!/bin/bash
set -e
rm -f /tmp/impacted_rules 
MUTE=yes ./get_kind_impacted rule  $1 $2

if [ -s "/tmp/impacted_rules" ] 
then
	echo ""
    echo ""
    echo "Building"
    cat  /tmp/impacted_rules  | xargs -L 1 bazel build   
else
	echo ""
    echo ""
    echo "No binary impacted... (ignoring)"
fi
