#!/bin/bash
set -e
./get_kind_impacted binary


if [ -s "/tmp/impacted_rules" ] 
then
	echo ""
    echo ""
    echo "Building"
    cat  /tmp/impacted_rules  | xargs bazel build 
else
	echo ""
    echo ""
    echo "No binary impacted... (ignoring)"
fi