#!/bin/bash
set -e
echo "### SANITY ###"
bazel query "deps(//...)" > /dev/null

echo ""
echo ""
echo ""
echo "### BUILDING ###"
./build_impacted

echo ""
echo ""
echo ""
echo "### TESTING ###"
./test_impacted

echo ""
echo ""
echo "" 
echo "### DEPLOYING ###"
./deploy_impacted
