#!/bin/bash




HEADP=${1:-production_pointer}
HEAD=$2 

set -e
echo ""
echo ""
echo "### Changed Files ###"
git fetch --tag
sleep 2
git diff --name-only $HEADP $HEAD | less

echo ""
echo ""
echo "### SANITY ###"
bazel query "deps(//...)" > /dev/null

echo ""
echo ""
echo "### BUILDING ###"
.ci/build_impacted $HEADP $HEAD


echo ""
echo ""
echo "### TESTING ###"
.ci/test_impacted $HEADP $HEAD

echo ""
echo ""
echo "### Push Impacted ###"
.ci/push_impacted $HEADP $HEAD

echo ""
echo ""
echo ""
echo "### Creating Artifacts ###"
.ci/artifact_impacted $HEADP $HEAD

echo ""
echo ""
echo "" 
echo "### Packaging Impacted Applications ###"
find -L ./bazel-bin -name "APPLICATION.manifest" -delete
.ci/list_applications_impacted  $HEADP $HEAD| xargs -L 1 bazel build  --logging 0


# echo ""
# echo ""
# echo ""
# echo "### Deploying Impacted ###"
# # ./deploy_impacted  $HEADP $HEAD




