#!/bin/bash

find -L ./bazel-bin -name "APPLICATION.manifest" > .changed_applications
cat .changed_applications
set -e
# ./get_kind_impacted _run_all 
PWD=$(pwd)
rm -rf /tmp/current_deploy
mkdir -p /tmp/current_deploy
echo ""
echo ""

while read artifact; do
  echo "Deploying: $artifact"
  rm -rf /tmp/current_deploy
  mkdir -p /tmp/current_deploy
  ZIP_ARTIFACT=$(cat $artifact | cut -d " " -f 2)
  unzip $ZIP_ARTIFACT -d /tmp/current_deploy
  
  cd /tmp/current_deploy
  chart=(*CHART_chart.tar.gz)
  namespace=$(echo $chart | sed 's/_CHART_chart.tar.gz$//')
  echo "Deployin $chart in $namespace"
  
  kubectl create namespace $namespace 2>/dev/null || true
  mkdir templates
  helm template $namespace $chart  -f sha256.yaml -f local.yaml > manifest.yaml
  kubectl apply -n  $namespace -f manifest.yaml
  echo "Images:"
  cat sha256.yaml
  cd $PWD
  echo ""
  echo ""
done <.changed_applications