#!/bin/bash
IMPLICIT="--noimplicit_deps"
case $1 in
        -f) export IMPLICIT=""            
        ;;
        *)  export IMPLICIT="--noimplicit_deps --notool_deps"
esac

> /tmp/graph_rules.in
bazel query 'kind(rule,deps(...))' $IMPLICIT --output graph > /tmp/graph_rules.in && \
dot -Tpng < /tmp/graph_rules.in > dependency_rules.png
#'filter("symlinks",deps(...))'
> /tmp/graph_all.in
bazel query 'filter("^(?!.*(symlinks|symlinks|nvs|mvc)).*$",deps(...))' $IMPLICIT --output graph > /tmp/graph_all.in && \
dot -Tpng < /tmp/graph_all.in > dependency.png

echo ""
echo "==== Universe Packages ===="
bazel query '...' --output package
echo ""
echo "==== Universe Rules ===="
bazel query 'kind(rule, //...)' --output label_kind


## --universe_scope=