#!/bin/bash
IMPLICIT="--noimplicit_deps"
case $1 in
        -f) export IMPLICIT=""            
        ;;
        *)  export IMPLICIT = "--noimplicit_deps"
esac

bazel query 'deps(...)' $IMPLICIT --output graph > /tmp/graph.in && \
dot -Tpng < /tmp/graph.in > dependency.png

echo ""
echo "==== Universe Packages ===="
bazel query '...' --output package
echo ""
echo "==== Universe Rules ===="
bazel query 'kind(rule, //...)' --output label_kind


## --universe_scope=