#!/bin/bash
> /tmp/changed_files
git diff --name-only $2 $3 > /tmp/changed_files

rm -f /tmp/impacted_rules_tmp   2> /dev/null
rm -f /tmp/impacted_rules  2> /dev/null

while read p; do
  if [ "$MUTE" != "yes" ]
  then
    echo "Fetching $p"
  fi
  bazel query "kind($1, rdeps(//..., $p))" 2> /dev/null >> /tmp/impacted_rules_tmp
done < /tmp/changed_files

(cat /tmp/impacted_rules_tmp | sort | uniq) > /tmp/impacted_rules 
if [ "$MUTE" != "yes" ]
then
  cat /tmp/impacted_rules 
fi

# echo " " >>  loggerlib/pretify.py 
# ./get_kind_impacted binary  756dbdc073430ee53d9ed1b227ac6155c6f4bfea
# cat  /tmp/impacted_rules  | xargs bazel build
# cat  /tmp/impacted_rules  | xargs bazel test

# ./get_kind_impacted _run_all 
# cat  /tmp/impacted_rules | grep .apply  | xargs bazel run 