#!/bin/bash
cat <<EOF
CURRENT_TIME $(date +%s)
RANDOM_HASH $(cat /dev/urandom | head -c16 | md5sum 2>/dev/null | cut -f1 -d' ')
STABLE_GIT_COMMIT $(git rev-parse HEAD)
STABLE_USER_NAME $USER

# This can be overriden by users if they "export VAR2_OVERRIDE"
#VAR2 ${VAR2_OVERRIDE:-default-value2}
EOF

