
apiVersion: networking.k8s.io/v1beta1
kind: git
metadata:
  name: weave
  annotations:
   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /weave
        backend:
          serviceName: weave-weave-chart
          servicePort: 80