
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: weave
#   annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: weave
    http:
      paths:
      - path: /
        backend:
          serviceName: weave-weave-chart
          servicePort: 80