#!/bin/bash

git fetch --tag
if ! git diff --quiet ; then
  echo 'The current repository is dirty'
  #exit 1
fi


HEADP=${1:-production_pointer}
HEAD=$2 

cd .ci
set -e
echo ""
echo ""
echo ""
echo "### Changed Files ###"
git diff --name-only $HEADP $HEAD

echo ""
echo ""
echo ""
echo "### SANITY ###"
bazel query "deps(//...)" > /dev/null

echo ""
echo ""
echo ""
echo "### BUILDING ###"
./build_impacted


echo ""
echo ""
echo ""
echo "### TESTING ###"
./test_impacted $HEADP $HEAD

echo ""
echo ""
echo ""
echo "### Push Impacted ###"
./push_impacted $HEADP $HEAD

echo ""
echo ""
echo ""
echo "### Creating Artifacts ###"
./artifact_impacted $HEADP $HEAD

echo ""
echo ""
echo "" 
echo "### Packaging Impacted Applications ###"
find -L ./bazel-bin -name "APPLICATION.manifest" -delete
./list_applications_impacted  $HEADP $HEAD| xargs -L 1 bazel build  --logging 0


# echo ""
# echo ""
# echo ""
# echo "### Deploying Impacted ###"
# # ./deploy_impacted  $HEADP $HEAD




