pipeline {
    agent any;
    environment {
    DOCKERHUB_CREDS = credentials('dockerhub')
    GITHUB_CREDS = credentials('github_artifact_token')
    }
    stages {
        stage('Computing Changes') {
            steps {
                sh  """
                    echo ""
                    echo ""
                    echo ""
                    git fetch --tag
                    echo "Tags:"
                    git tag
                    echo "### Changed Files ###"
                    echo "production_pointer is in:"
                    git rev-list -n 1 production_pointer
                    git diff --name-only production_pointer \${GIT_COMMIT}
                    echo "### Generating Dependency Graph ###"
                    ./generates_deps
                    """
                archiveArtifacts artifacts: '*.png', fingerprint: true
            }
        }
        stage('Impacted Unit Test') {
            steps {
                echo 'Testing..'
                sh  """
                    echo ""
                    echo ""
                    echo ""
                    echo "### TESTING ###"
                    ./test_impacted production_pointer \${GIT_COMMIT}
                    """
            }
        }
        stage('Publishing Impacted Images') {
            steps {
                echo 'Pushing Imagess..'
                sh  """
                    echo ""
                    echo ""
                    echo ""
                    echo "### Push Impacted ###"
                    docker login --username \${DOCKERHUB_CREDS_USR} -p  \${DOCKERHUB_CREDS_PSW}
                    ./push_impacted production_pointer \${GIT_COMMIT}
                    """
            }
        }

        stage('Repackaging Impacted Applications') {
            steps {
                echo 'Re-packaging..'
                sh  """
                    echo ""
                    echo ""
                    echo ""
                    echo "### Creating Artifacts ###"
                    ./artifact_impacted production_pointer \${GIT_COMMIT}
                    echo "### Packaging Impacted Applications ###"
                    echo ""
                    echo ""
                    echo ""
                    find -L ./bazel-bin -name "APPLICATION.manifest" -delete
                    ./list_applications_impacted   production_pointer \${GIT_COMMIT}| xargs -L 1 bazel build  --logging 0
                    """
            }
        }


        stage('Geting Artifact Repo') {
            steps {
                sh  """
                    cd /tmp
                    git clone https://\${DOCKERHUB_CREDS_USR}:\${DOCKERHUB_CREDS_PSW}@github.com/OStartUp/artifacts.git
                    """
            }   
        }

        stage('Publishing Changes') {
            steps {
                echo 'Publishing..'
                sh  """
                    find -L ./bazel-bin -name "APPLICATION.manifest" > .changed_applications
                    cat .changed_applications
    
                    rm -rf artifacts
                    mkdir -p artifacts
                    while read artifact; do
                        ROOT_DIR=\$(pwd)
                        echo "Publishing: \${artifact}"
                        ZIP_ARTIFACT=\$(cat \${artifact} | cut -d " " -f 2)
                        cp -v \${ZIP_ARTIFACT} artifacts/
                        
                        echo "Expanding: \$ZIP_ARTIFACT"
                        rm -rf /tmp/current_deploy
                        mkdir -p /tmp/current_deploy
                        unzip \$ZIP_ARTIFACT -d /tmp/current_deploy

                        cd /tmp/current_deploy
                        chart=(*_chart.tar.gz)
                        chart_name=\$(echo \$chart | sed 's/_chart.tar.gz\$//')
                        
                        echo "Creating manifest for \$chart in \$chart_name namespace"
                        helm template \$chart_name \$chart  -f sha256.yaml -f local.yaml > manifest.yaml
                        mkdir -p /tmp/artifacts/\${chart_name}
                        cp manifest.yaml /tmp/artifacts/\${chart_name}
                        cd /tmp/artifacts
                        git add .
                        git commit -a -m "New artifact"
                        git push
                        cd -
                        echo "Images:"
                        cat sha256.yaml
                        cd \$ROOT_DIR 2> /dev/null
  
                                                
                    done < .changed_applications
                    """
                archiveArtifacts artifacts: 'artifacts/*', fingerprint: true
            }
        }
    }

    post {
        always {
           archiveArtifacts artifacts: '**/*.log', fingerprint: true
        }
        success {
            echo 'I succeeeded!'
        }
        unstable {
            echo 'I am unstable :/'
        }
        failure {
            echo 'I failed :('
        }
        changed {
            echo 'Things were different before...'
        }   
    }
}

