#!/bin/bash
> /tmp/impacted_rules 
MUTE=yes ./get_kind_impacted rule  $1 $2 
cat  /tmp/impacted_rules | grep "_PUSHER" > /tmp/pushers

set -e
if [ -s "/tmp/pushers" ] 
then
    while read pusher; do
    echo "Pushing: $pusher"
    bazel run  $pusher
    done < /tmp/pushers
    echo "--"
else
    echo "No pushers to run"
fi


