#!/bin/bash

MUTE=yes .ci/get_kind_impacted test $1 $2


if [ -s "/tmp/impacted_rules" ] 
then
	echo ""
    echo ""
    echo "Testing changes"
    cat  /tmp/impacted_rules  | xargs -L 1 bazel test 
else
	echo ""
    echo ""
    echo "No tests impacted... (ignoring)"
fi