apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: echo-deploy
    spec:
      containers:
        - name: echo-server
          image: marcecaro/echo@{{ (index .Values.sha256 "marcecaro/echo") }}
          imagePullPolicy: Always
          # ports:
          # - containerPort: 5000
 